nodes:
  indexer:
    - name: node-1
      ip: 172.20.0.15
  server:
    - name: wazuh-master
      ip: 172.20.0.7
      node_type: master
    - name: wazuh-worker1
      ip: 172.20.0.5
      node_type: worker
    - name: wazuh-worker2
      ip: 172.20.0.4
      node_type: worker
