# Include the PyServer team-owned directories.
include = [
    "framework/**/*.py",
    "apis/**/*.py",
    "wodles/**/*.py",
    "integrations/**/*.py",
]
line-length = 120
indent-width = 4
target-version = "py310"

[lint]
select = [
    "E4", # Imports
    "E7", # Statements
    "E9", # IO error
    "F", # Pyflakes rules
    "I001", # Unsorted imports
    "C901", # McCabe complexity
    "D", # Pydocstyle rules
    "N", # Pep8 rules
]
ignore = [
    "F405", # Star imports
    "D100", # Module comment
    "D107", # Init docstring
    "D203", # Blank line before docstring
    "D204", # Blank line after docstring
    "D205", # Blank line between summary and description
    "D213", # Summary and description second line start
    "D413", # Blank line after last section
    "N818", # Error suffix
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
"wodles/**/*.py" = ["E402"]
"apis/server_management/server_management_api/test/integration/env/configurations/**/*.py" = ["E402"]
"__init__.py" = ["F401"]

[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = 120
