language: c

env:
- USER_LANGUAGE="en"
- USER_NO_STOP="y"
- USER_INSTALL_TYPE="server"
- USER_DIR="/var/ossec"
- USER_DELETE_DIR="y"
- USER_ENABLE_ACTIVE_RESPONSE="y"
- USER_ENABLE_SYSCHECK="y"
- USER_ENABLE_ROOTCHECK="y"
- USER_ENABLE_OPENSCAP="y"
- USER_ENABLE_SYSCOLLECTOR="y"
- USER_UPDATE="n"
- USER_SERVER_IP="1.2.3.4"
- USER_CA_STORE="/path/to/my_cert.pem" 

before_script:
- sudo apt-get update -qq
- sudo apt-get -y install build-essential

script:
- sudo USER_LANGUAGE="en" USER_NO_STOP="y" USER_INSTALL_TYPE="agent" USER_DIR="/var/ossec" USER_DELETE_DIR="y" USER_ENABLE_ACTIVE_RESPONSE="y" USER_ENABLE_SYSCHECK="y" USER_ENABLE_ROOTCHECK="y" USER_ENABLE_OPENSCAP="y" USER_ENABLE_SYSCOLLECTOR="y" USER_UPDATE="n" USER_SERVER_IP="1.2.3.4" USER_CA_STORE="/path/to/my_cert.pem" ./install.sh


