exclude: '^src/|^tools/|^tests/'
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      # Run linter
      - id: ruff
        args: [ --fix ]
      # Run formatter
      - id: ruff-format
  - repo: local
    hooks:
      - id: check-comms-api-spec
        name: Check Comms API spec
        entry: python apis/tools/doc/generate_comms_api_spec.py --output-file docs/ref/modules/communications/spec.yaml
        language: system
        pass_filenames: false