name: environment/wazuh/0

decoders:
  # First level decoders by queue
  - decoder/queue-syscollector/0
  - decoder/queue-sca/0
  - decoder/queue-fim/0
  - decoder/queue-syslog/0
  - decoder/queue-dbsync/0
  - decoder/queue-localfile/0
  - decoder/queue-rootcheck/0
  - decoder/queue-ciscat/0

  # General format decoders
  - decoder/json/0

  # Internal decoders
  - decoder/dbsync/0
  - decoder/fim/0
  - decoder/fim-event/0
  - decoder/fim-scan/0
  - decoder/rootcheck/0
  - decoder/sca/0
  - decoder/ciscat/0
  - decoder/syscollector-base/0
  - decoder/syscollector-dbsync-network-protocol/0
  - decoder/syscollector-dbsync-osinfo/0
  - decoder/syscollector-dbsync-osinfo-inserted/0
  - decoder/syscollector-dbsync-ports/0
  - decoder/syscollector-dbsync-ports-inserted/0
  - decoder/syscollector-dbsync-processes/0
  - decoder/syscollector-dbsync-processes-inserted/0
  - decoder/syscollector-dbsync-base/0
  - decoder/syscollector-dbsync-hotfixes/0
  - decoder/syscollector-dbsync-hotfixes-inserted/0
  - decoder/syscollector-dbsync-hwinfo/0
  - decoder/syscollector-dbsync-hwinfo-inserted/0
  - decoder/syscollector-dbsync-network-address/0
  - decoder/syscollector-dbsync-network-address-inserted/0
  - decoder/syscollector-dbsync-network-iface/0
  - decoder/syscollector-dbsync-network-iface-inserted/0
  - decoder/syscollector-dbsync-network-protocol-inserted/0
  - decoder/syscollector-dbsync-packages/0
  - decoder/syscollector-dbsync-packages-inserted/0
  - decoder/syscollector-hardware/0
  - decoder/syscollector-hotfix/0
  - decoder/syscollector-netinfo/0
  - decoder/syscollector-network/0
  - decoder/syscollector-network-end/0
  - decoder/syscollector-network-ip/0
  - decoder/syscollector-osinfo/0
  - decoder/syscollector-port/0
  - decoder/syscollector-port-del/0
  - decoder/syscollector-port-save/0
  - decoder/syscollector-process/0
  - decoder/syscollector-process-del/0
  - decoder/syscollector-process-save/0
  - decoder/syscollector-program/0
  - decoder/syscollector-program-del/0
  - decoder/syscollector-program-save/0

  # Enrich events with host info
  - decoder/agent-event-enrichment/0
  - decoder/dbsync-host-data/0
  - decoder/kvdb-agent-update/0
  - decoder/syscollector-dbsync-host-data/0

  # Service decoders
  - decoder/syslog/0
  - decoder/sonicwall-firewall/0
  # TODO uncomment when the fields are added to the schema
  # - decoder/sonicwall-firewall-generated/0
  - decoder/redis/0

  # Postgresql decoders
  - decoder/postgresql-csv/0
  - decoder/postgresql-csv-msg-parse/0

  # NGINX decoder
  - decoder/nginx-access-base/0
  - decoder/nginx-access/0
  - decoder/nginx-error/0

  # AWS decoder
  - decoder/aws/0
  - decoder/aws-s3/0
  - decoder/aws-cloudtrail/0
  - decoder/aws-elb/0

  # Auditd
  - decoder/auditd/0
  - decoder/auditd-kv/0

outputs:
  - output/file-output/0
