name: decoder/windows_security/0

sources: 
  - decoder/windows_event_channel/0

metadata:
  description: Decoder for Windows Security events

check:
  - ~event_channel.Event.System.Provider.@Name: Microsoft-Windows-Security-Auditing


normalize:
 - map:
    - event.module: security
    - event.code: $~event_channel.Event.System.EventID.#text

    # Set categorization fields
    - event: +kvdb_get_merge/win_security_categories/$~event_channel.Event.System.EventID.#text
    
    # Set Logon Type
    - event.logon: +kvdb_get/win_logon_types/$~event_channel.Event.EventData.LogonType
    
    # Set User Account Control
    # NewUacValue 
    # Correct implementation needs bitwise operations - Opting to use raw value
    - event.UserAccountControl: $~event_channel.Event.EventData.NewUacValue
    
    
    # Set Kerberos Ticket Options
    # TicketOptionsDescription - Needs bitwise operations

    # Set Kerberos Encryption Types
    - event: +kvdb_get_merge/win_security_ticket_encryption_types/$~event_channel.Event.EventData.TicketEncryptionType
    
    # Set Kerberos Ticket Status Codes
    - event.StatusDescription: +kvdb_get_merge/win_security_kerberos_status_types/$~event_channel.Event.EventData.Status
    
    # Set Service Type and Name
    # Service related fields
    - event.service.name: $~event_channel.Event.EventData.ServiceName
    - event.service.type: +kvdb_get_merge/win_security_service_types/$~event_channel.Event.EventData.ServiceType
    
    # Set Audit Information
    # Event sub category - Need to clean guid
    - event.Category: +kvdb_get_merge/win_security_category_guids/$~event_channel.Event.EventData.SubcategoryGuid
    - event.SubCategory: +kvdb_get_merge/win_security_subcategory_guids/$~event_channel.Event.EventData.SubcategoryGuid

    # Set trust type
    - event.trustType: +kvdb_get/win_trust_types/$~event_channel.Event.EventData.TdoType

    # Set Trust Direction
    - event.trustDirection: +kvdb_get/win_trust_direction/$~event_channel.Event.EventData.TdoDirection

    # Set Trust Attributes
    - event.trustAttribute: +kvdb_get/win_trust_attribute/$~event_channel.Event.EventData.TdoAttributes

    - event.logon.id: $~event_channel.Event.EventData.SubjectLogonId

    - event.PrivilegeList: +s_to_array/$~event_channel.Event.EventData.PrivilegeList// 

    - event.user.target.name: $~event_channel.Event.EventData.OldTargetUserName
    - event.user.changes.name: $~event_channel.Event.EventData.NewTargetUserName
    - event.related.user: +a_append/$~event_channel.Event.EventData.NewTargetUserName
    - event.related.user: +a_append/$~event_channel.Event.EventData.OldTargetUserName 

    - event.time_created: $~event_channel.Event.System.TimeCreated.@SystemTime

    # map helper arrays
    - ~id_target_user_array: ["4624","4625","4634","4647","4648","4768","4769","4770","4771","4776","4964"]
    - ~id_memberName_array: ["4727", "4728", "4729", "4730", "4731", "4732", "4733", "4734", "4735",
                              "4737", "4744", "4745", "4746", "4747", "4748", "4749", "4750", "4751",
                              "4752", "4753", "4754", "4755", "4756", "4757", "4758", "4759", "4760",
                              "4761", "4762", "4763", "4764", "4799"]
    - ~id_copy_subject_user_array: ["4657", "4670", "4672", "4673", "4674", "4688", "4689", "4697",
              "4698", "4699", "4700", "4701", "4702", "4706", "4707", "4713",
              "4716", "4717", "4718", "4719", "4720", "4722", "4723", "4724",
              "4725", "4726", "4727", "4728", "4729", "4730", "4731", "4732",
              "4733", "4734", "4735", "4737", "4738", "4739", "4740", "4741",
              "4742", "4743", "4744", "4745", "4746", "4747", "4748", "4749",
              "4750", "4751", "4752", "4753", "4754", "4755", "4756", "4757",
              "4758", "4759", "4760", "4761", "4762", "4763", "4764", "4767",
              "4781", "4798", "4799", "4817", "4904", "4905", "4907", "4912",
              "4648"]
    - ~id_copy_target_user_array: ["4670", "4720", "4722", "4723", "4724", "4725",
              "4726", "4738", "4740", "4767", "4798", "4817", "4907"]
    - ~id_rename_common_auth_fields: ["1100", "1102", "1104", "1105", "1108", "4624", "4648", "4625",
              "4670", "4673", "4674", "4689", "4697", "4719", "4720", "4722",
              "4723", "4724", "4725", "4726", "4727", "4728", "4729", "4730",
              "4731", "4732", "4733", "4734", "4735", "4737", "4738", "4740",
              "4741", "4742", "4743", "4744", "4745", "4746", "4747", "4748",
              "4749", "4750", "4751", "4752", "4753", "4754", "4755", "4756",
              "4757", "4758", "4759", "4760", "4761", "4762", "4763", "4764",
              "4767", "4768", "4769", "4770", "4771", "4798", "4799", "4817",
              "4904", "4905", "4907", "4912"]
     - ~id_related_user:  ["4688", "4720", "4722", "4723", "4724", "4725", "4726", "4738",
         "4740", "4767", "4798"]

    # Decode message table
    # Failure reason for logon
 - check:
       - ~event_channel.Event.EventData.FailureReason: +ef_exists
   map:
        - event.logon.failure.reason: +kvdb_get/win_failure_codes_description/$~event_channel.Event.EventData.FailureReason
    # Audit Policy Changes
    # Needs for each element of an array
    #- check:
    #  - ~event_channel.Event.EventData.AuditPolicyChanges: +ef_exists
    #  map:
    #    - ~tmp.array_policy_changes: +s_to_array/$~event_channel.Event.EventData.AuditPolicyChanges/,
    #    - event.AuditPolicyChangesDescription: +kvdb_for_each/win_failure_codes_description/$~tmp.array_policy_changes
    # Access List
 - check:
      - ~event_channel.Event.EventData.AccessList: +ef_exists
   map:
        - _tmp.array_access_masks: +s_to_array/$~event_channel.Event.EventData.AccessMask/,
        #- event.AccessMask: +kvdb_for_each/win_failure_codes_description/$_tmp.array_access_masks
    #
    # Access Mask - # Requires bitwise operations
    #- check:
    #  - ~event_channel.Event.EventData.AccessMask: +ef_exists
    #  map:
    #   - _tmp.array_policy_changes: +s_to_array/$~event_channel.Event.EventData.AuditPolicyChanges/ #whitespace spearator?
    #   - _tmp.accesMask |= _tmp.array_policy_changes #bitwise OR add?
       

    # Conditional logon status and substatus
    # 4625 and 4776 Set Status and SubStatus
 - check: event.code==4625 OR event.code==4776
   map:
        - event.logon.failure.status: +kvdb_get/win_logon_status/$~event_channel.Event.EventData.Status
        - event.logon.failure.sub_status: +kvdb_get/win_logon_status/$~event_channel.Event.EventData.SubStatus

    # Add Session Events
 - check: event.code!=4778 OR event.code!=4779
   map:
        # AccountName to user.name and related.user
        - event.user.name: ~event_channel.Event.EventData.AccountName
        - event.related.user: ~event_channel.Event.EventData.AccountName
        # AccountDomain to user.domain
        - event.user.domain: ~event_channel.Event.EventData.AccountDomain
        # ClientAddress to source.ip and related.ip
        - event.source.ip: ~event_channel.Event.EventData.ClientAddress
        - event.related.ip: ~event_channel.Event.EventData.ClientAddress
        # ClientName to source.domain
        - event.source.domain: ~event_channel.Event.EventData.ClientName
        # LogonID to winlog.logon.id
        - event.logon.id: ~event_channel.Event.EventData.LogonID
    
    # Copy Target User
    
 - check:
      - ~id_target_user_array: +a_contains/$event.code
   map:
      - ~is_copy_target_user: true
    # TargetUserSid to user.id or user.target.id  
 - check: 
      - event.user.id: +ef_not_exists
      - ~is_copy_target_user: +t_is_true
   map:
        - event.user.id: ~event_channel.Event.EventData.TargetUserSid
        - event.user.id: ~event_channel.Event.EventData.TargetSid
 - check:
      - event.user.id: +ef_exists
      - ~id_array: +t_is_true
   map:
        - event.user.target.id: ~event_channel.Event.EventData.TargetUserSid
        - event.user.target.id: ~event_channel.Event.EventData.TargetSid
 # TargetUserName to related.user and user.name or user.target.name
 - check: 
      - event.user.name: +ef_not_exists
      - ~is_copy_target_user: +t_is_true
   map:
        - event.user.name: ~event_channel.Event.EventData.TargetUserName
 - check: 
      - event.user.name: +ef_exists
      - ~is_copy_target_user: +t_is_true
   map:
        - event.user.target.name: ~event_channel.Event.EventData.TargetUserName
 - check: 
      - ~is_copy_target_user: +t_is_true  
   map:
        - event.related.user: +a_append/$~event_channel.Event.EventData.TargetUserName 
    # TargetUserDomain to user.domain or user.target.domain
 - check:
      - ~is_copy_target_user: +t_is_true
      - event.user.domain: +ef_not_exists
   map:
        - event.user.domain: ~event_channel.Event.EventData.TargetDomainName
 - check:
      - ~is_copy_target_user: +t_is_true
      - event.user.domain: +ef_exists
   map:
        - event.user.target.domain: ~event_channel.Event.EventData.TargetDomainName

    # Copy MemberName to User and User to Group
 - check:
        - ~id_memberName_array: +a_contains/$event.code
   map:
        - is_copy_MemberName: true
        - ~split_memberName: +s_to_array/$~event_channel.Event.EventData.MemberName/,
        - ~split_memberName.0: +s_replace/CN=// 
        - event.member.name: $~split_memberName.0
        - event.group.id: $~event_channel.Event.EventData.TargetUserSid
        - event.group.id: $~event_channel.Event.EventData.TargetSid 
        - event.group.name: $~event_channel.Event.EventData.TargetUserName
        - ~event_channel.Event.EventData.TargetDomainName: +s_replace/DC=//
        - event.goup.domain: $~event_channel.Event.EventData.TargetDomainName
        - event.user.target.group.id: event.group.id
        - event.user.target.group.name: event.group.name
        - event.user.target.group.domain: event.group.domain
 - check:   
        # - ~split_memberName: +a_ge/4
        - is_copy_MemberName: +t_is_true
   map:
        - ~split_memberName.3: +s_replace/DC=// 
        - event.user.target.domain: $~split_memberName.3

 # Copy Target User to Computer Object
 - check: event.code==4741 OR event.code==4742 OR event.code==4743
   map:
    - event.computerObject.id: $~event_channel.Event.EventData.TargetSid
    - event.computerObject.name: $~event_channel.Event.EventData.TargetUserName
    - event.computerObject.domain: $~event_channel.Event.EventData.TargetDomainName
        
 - check: event.code==4634 OR event.code==4647 OR event.code==4964
   map:
    - event.logon.id: $~event_channel.Event.EventData.TargetLogonId 
 
 # Copy Subject User from Event Data
 - check: 
     - ~id_copy_subject_user_array: +a_contains/$event.code
   map:
     - event.user.id: $~event_channel.Event.EventData.SubjectUserSid
     - event.related.user: +a_append/$~event_channel.Event.EventData.SubjectUserName
     - event.user.domain: $~event_channel.Event.EventData.SubjectDomainName

 # Copy Target User to Target
 - check: 
    - ~id_copy_target_user_array: +a_contains/$event.code
   map:
     - event.user.target.id: $~event_channel.Event.EventData.TargetSid
     - ~name_part: +s_to_array/$~event_channel.Event.EventData.TargetUserName/@
     - event.user.target.name: $~name_part.0
     - event.related.user: +a_append/$event.user.target.name
     - event.user.target.domain: $~event_channel.Event.EventData.TargetDomainName

# Copy Target User to Effective
 - check: event.code==4741 OR event.code==4742
   map:
     - event.user.effective.id: $~event_channel.Event.EventData.TargetUserSid
     - ~name_part: +s_to_array/$~event_channel.Event.EventData.TargetUserName/@
     - event.user.effective.name: $~name_part.0
     - event.related.user: +a_append/$event.user.effective.name
     - event.user.effective.domain: $~event_channel.Event.EventData.TargetDomainName

# Copy Subject User from user_data
 - check: event.code==1102
   map:
     - event.user.id: $~event_channel.Event.EventData.SubjectUserSid
     - event.user.name: $~event_channel.Event.EventData.SubjectUserName
     - event.user.related.user: +a_append/$~event_channel.Event.EventData.SubjectUserName
     - event.user.domain: $~event_channel.Event.EventData.SubjectDomainName

# Rename Common Auth Fields
 - check:
     - ~id_rename_common_auth_fields: +a_contains/$event.code
   map:
     - event.process.pid: $~event_channel.Event.EventData.ProcessId
     - event.process.executable: $~event_channel.Event.EventData.ProcessName
     - event.source.ip: $~event_channel.Event.EventData.IpAddress
     - event.source.port: $~event_channel.Event.EventData.IpPort
     - event.source.domain: $~event_channel.Event.EventData.WorkstationName
     - event.related.ip: $~event_channel.Event.EventData.ClientAddress
     # - ~process_name: +s_to_array/$event.process.executable/\
     # - event.process.name: $~process_name.-1

# Process Event 4688
 - check: event.code==4688 
  map:
     - event.process.pid: $~event_channel.Event.EventData.NewProcessId
     - event.process.executable: $~event_channel.Event.EventData.NewProcessName
     - event.process.parent.executable: $~event_channel.Event.EventData.ParentProcessName
     # - ~process_name: +s_to_array/$event.process.executable/\
     # - event.process.name: $~process_name.-1
     # - ~process_name: +s_to_array/$event.process.parent.executable/\
     # - event.process.parent.name: $~process_name.-1 
     - event.process.parent.pid: $~event_channel.Event.EventData.ProcessId
     # - event.process.args: # rather hard to get maybe use regex?
     - event.process.commands_line: $~event_channel.Event.EventData.CommandLine
     - event.related.user: +a_append/$~event_channel.Event.EventData.TargetUserName

 - check: event.code==4624 OR event.code==4648
   map:
     - event.related.user: $~event_channel.Event.EventData.SubjectUserName

 - check: 
      - ~id_related_user: +a_contains/$event.code
   map:
      - event.related.user: $~event_channel.Event.EventData.TargetUserName

 - map:
     - event.related.ip: event.source.ip

 # Object Policy Change and SidListDesc
 # - check: event.code==4670 OR event.code==4817 OR event.code==4907 OR event.code==4808

