name: Wazuh Keystore

on:
  workflow_dispatch:
  pull_request:
  # Pull request events
    types: [synchronize, opened, reopened, ready_for_review]
  # Path filtering
    paths:
      - ".github/workflows/4_testcomponent_keystore.yml"
      - "src/shared_modules/keystore/**"
      - "src/shared_modules/utils/**"

jobs:
  wazuh-keystore-qa:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Compile keystore
        run: |
          make deps TARGET=server -j2 -C src/
          make libwazuhext.so TARGET=server -j2 -C src/
          mkdir -p src/shared_modules/keystore/build
          cmake -S src/shared_modules/keystore -B  src/shared_modules/keystore/build -DSRC_FOLDER=$(pwd)/src
          cmake --build src/shared_modules/keystore/build -j2
          find . -name "wazuh-keystore-testtool" -exec mv {} src/ \;

      - name: Install dependencies
        run: |
          pip install -r src/shared_modules/keystore/qa/requirements.txt

      - name: Run tests
        run: |
          python -m pytest -vv src/shared_modules/keystore/qa/ --log-cli-level=DEBUG
