name: Syscollector test on Ubuntu

on:
  workflow_dispatch:
  pull_request:
    paths:
        - ".github/workflows/4_testcomponent_sysinfo-linux.yml"
        - "src/data_provider/**"
        - "src/shared_modules/**"
        - "src/wazuh_modules/syscollector/**"
        - "src/Makefile"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: "Install a compatible CMake"
        uses: ./.github/actions/reinstall_cmake
      # Build wazuh agent for linux.
      - name: Build wazuh agent for linux
        run: |
          make deps -C src TARGET=agent -j2
          make -C src build_syscollector TARGET=agent -j2
      - name: Install dependencies
        run: |
          pip install -r src/data_provider/qa/requirements.txt
      - name: Run tests
        run: |
          cd src/data_provider
          python -m pytest -vv qa/
