name: 4_testintegration_inventory-harvester

on:
  workflow_dispatch:
  pull_request:
  # Pull request events
    types: [synchronize, opened, reopened, ready_for_review]
  # Path filtering
    paths:
      - ".github/workflows/4_testintegration_inventory-harvester.yml"
      - ".github/actions/vulnerability_scanner_deps/action.yml"
      - ".github/actions/build_target_cpp/action.yml"
      - "src/shared_modules/router/**"
      - "src/shared_modules/indexer_connector/**"
      - "src/wazuh_modules/inventory_harvester/**"
      - "src/shared_modules/utils/**"

jobs:
  inventory-harvester-qa:
    runs-on: ubuntu-22.04

    steps:
      - name: Cancel previous runs
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_after_successful_duplicate: 'false'

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Project dependencies
        uses: ./.github/actions/vulnerability_scanner_deps

      - name: Inventory harvester - Build tooling
        uses: ./.github/actions/build_target_cpp
        with:
          target: "inventory_harvester_testtool"
          test: "false"
          asan: "false"

      # Install python dependencies
      - name: Install dependencies
        run: |
          pip install -r src/wazuh_modules/inventory_harvester/qa/requirements.txt

      - name: Run tests
        run: |
          cd src
          echo "{}" > states_update_mappings.json
          echo '{"index_patterns":["wazuh-states-*"],"priority":1,"template":{"settings":{},"mappings":{},"aliases":{}}}' > dummy_template.json
          python -m pytest -vv wazuh_modules/inventory_harvester/qa/ --log-cli-level=DEBUG
