run-name: Build wazuh-server packages on PR ${{ github.event.pull_request.number }}
name: Build wazuh-server packages on PR

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    branches:
      - main
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  package-build:
    if: ${{ !github.event.pull_request.draft }}
    strategy:
      fail-fast: false
      matrix:
        architecture: [amd64]
        system: [deb, rpm]
    uses: ./.github/workflows/packages-build-server.yml
    with:
      architecture: ${{ matrix.architecture }}
      system: ${{ matrix.system }}
    secrets: inherit
