name: 5_testcomponent_contentmanager

on:
  workflow_dispatch:
  pull_request:
  # Pull request events
    types: [synchronize, opened, reopened, ready_for_review]
  # Path filtering
    paths:
      - ".github/workflows/5_testcomponent_contentmanager.yml"
      - "src/shared_modules/utils/**"
      - "src/shared_modules/content_manager/**"

jobs:
  contentmanager-modules:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel previous runs
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_after_successful_duplicate: 'false'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Project dependencies
        uses: ./.github/actions/build_external_deps

      - name: Content manager - Build tests
        uses: ./.github/actions/build_target_cpp
        with:
          target: "content_manager_ctest"
          test: "true"
          asan: "false"

      - name: Content manager - Run tests
        uses: ./.github/actions/test_cpp
        with:
          target: "content_manager_ctest"
          valgrind: "true"


  inventory-harvester-asan:
    strategy:
      matrix:
        os: [ ubuntu-24.04, ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cancel previous runs
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_after_successful_duplicate: 'false'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Project dependencies
        uses: ./.github/actions/build_external_deps

      - name: Content manager - Build tests
        uses: ./.github/actions/build_target_cpp
        with:
          target: "content_manager_ctest"
          test: "true"
          asan: "true"

      - name: Content manager - Run tests
        uses: ./.github/actions/test_cpp
        with:
          target: "content_manager_ctest"
          valgrind: "false"
