name: "5.X - Vulnerability Scanner - Integration tests"
on:
  workflow_dispatch:
  pull_request:
  # Pull request events
    types: [synchronize, opened, reopened, ready_for_review]
  # Path filtering
    paths:
      - ".github/workflows/5_testintegration_vulnerability-scanner.yml"
      - "src/wazuh_modules/vulnerability_scanner/**"
      - "src/shared_modules/utils/**"
      - "src/wazuh_modules/inventory_sync/**"

jobs:
  vulnerability-scanner-integration:
    runs-on: ubuntu-24.04
    env:
      OFFLINE_CONFIG_FILE: src/wazuh_modules/vulnerability_scanner/testtool/scanner/config.offline_content_generation.json
    steps:
      - name: Cancel previous runs
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_after_successful_duplicate: 'false'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install compatible CMake
        uses: ./.github/actions/reinstall_cmake

      - name: Builder external dependencies
        uses: ./.github/actions/build_external_deps

      - name: Vulnerability scanner - Test tool
        uses: ./.github/actions/build_target_cpp
        with:
          target: "vd_scanner_testtool"
          test: "false"
          asan: "false"

      - name: Inventory Sync - Test tool
        uses: ./.github/actions/build_target_cpp
        with:
          target: "inventory_sync_testtool"
          test: "false"
          asan: "false"

      - name: Generate reduced database
        run: |
          src/build/wazuh_modules/vulnerability_scanner/testtool/scanner/vd_scanner_testtool -c ${{ env.OFFLINE_CONFIG_FILE }} -d

          rm -rf queue/indexer
          rm -rf queue/sockets
          rm -rf queue/router
          rm -rf queue/vd_updater/tmp
          rm -rf queue/vd/reports
          rm -rf queue/vd/sync
          rm -rf queue/vd/deltas
          rm -rf queue/vd/state_track
          rm -rf queue/keystore
          rm -rf queue/vd/inventory
          rm -rf queue/vd/delayed
          rm -rf queue/vd/event

          mv queue src

      - name: Install dependencies
        run: |
          pip install -r src/wazuh_modules/vulnerability_scanner/qa/requirements.txt

      - name: Create folder for test logs
        run: |
          mkdir -p ${{ github.workspace }}/qa_logs

      - name: Run tests
        run: |
          cd src
          python -m pytest -vv wazuh_modules/vulnerability_scanner/qa/test_efficacy_log.py --log-cli-level=DEBUG
          rm -rf tmp

      - name: Upload log files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: QA log files
          path: ${{ github.workspace }}/qa_logs
