name: 5_testunit_router

on:
  workflow_dispatch:
  pull_request:
  # Pull request events
    types: [synchronize, opened, reopened, ready_for_review]
  # Path filtering
    paths:
      - ".github/workflows/5_testunit_router.yml"
      - "src/shared_modules/utils/**"
      - "src/shared_modules/router/**"

jobs:
  router-modules:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel previous runs
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_after_successful_duplicate: 'false'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Project dependencies
        uses: ./.github/actions/build_external_deps

      - name: Router - Build tests
        uses: ./.github/actions/build_target_cpp
        with:
          target: "router_utest"
          test: "true"
          asan: "false"

      - name: Router - Run tests
        uses: ./.github/actions/test_cpp
        with:
          valgrind: "true"
          target: "router_utest"

      - name: Router - Coverage
        uses: ./.github/actions/coverage_cpp
        with:
          path: src/shared_modules/router
          id: router

  router-asan:
    strategy:
      matrix:
        os: [ ubuntu-24.04, ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Project dependencies
        uses: ./.github/actions/build_external_deps

      - name: Router - Build tests
        uses: ./.github/actions/build_target_cpp
        with:
          target: "router_utest"
          test: "true"
          asan: "true"

      - name: Router - Run tests
        uses: ./.github/actions/test_cpp
        with:
          target: "router_utest"
          valgrind: "false"
