name: 5.X - Vulnerability Scanner - Component tests

on:
  workflow_dispatch:
  pull_request:
  # Pull request events
    types: [synchronize, opened, reopened, ready_for_review]
  # Path filtering
    paths:
      - ".github/workflows/5_testcomponent_vulnerability-scanner.yml"
      - "src/wazuh_modules/vulnerability_scanner/**"
      - "src/shared_modules/utils/**"

jobs:
  vulnerability-scanner-modules:
    runs-on: ubuntu-24.04
    steps:
      - name: Cancel previous runs
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_after_successful_duplicate: 'false'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install compatible CMake
        uses: ./.github/actions/reinstall_cmake

      - name: Builder external dependencies
        uses: ./.github/actions/build_external_deps

      - name: Vulnerability scanner - Build tests
        uses: ./.github/actions/build_target_cpp
        with:
          target: "vulnerability_scanner_component_tests"
          test: "true"
          asan: "false"

      - name: Vulnerability scanner - Run tests
        uses: ./.github/actions/test_cpp
        with:
          valgrind: "true"
          target: "vulnerability_scanner_component_tests"

  vulnerability-scanner-modules-asan:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install compatible CMake
        uses: ./.github/actions/reinstall_cmake

      - name: Builder external dependencies
        uses: ./.github/actions/build_external_deps

      - name: Vulnerability scanner - Build tests
        uses: ./.github/actions/build_target_cpp
        with:
          target: "vulnerability_scanner_component_tests"
          test: "true"
          asan: "true"

      - name: Vulnerability scanner - Run tests
        uses: ./.github/actions/test_cpp
        with:
          valgrind: "false"
          target: "vulnerability_scanner_component_tests"
