name: 5.X - Vulnerability Scanner - Unit tests

on:
  workflow_dispatch:
  pull_request:
  # Pull request events
    types: [synchronize, opened, reopened, ready_for_review]
  # Path filtering
    paths:
      - ".github/workflows/5_testunit_vulnerability-scanner.yml"
      - "src/wazuh_modules/vulnerability_scanner/**"

jobs:
  vulnerability-scanner-modules:
    runs-on: ubuntu-24.04
    steps:
      - name: Cancel previous runs
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_after_successful_duplicate: 'false'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install compatible CMake
        uses: ./.github/actions/reinstall_cmake

      - name: Builder external dependencies
        uses: ./.github/actions/build_external_deps

      - name: Build router
        uses: ./.github/actions/compile
        with:
          path: "src/shared_modules/router"

      - name: Build indexer connector tests
        uses: ./.github/actions/compile
        with:
          path: "src/shared_modules/indexer_connector"

      - name: Build content manager tests
        uses: ./.github/actions/compile
        with:
          path: "src/shared_modules/content_manager"

      # Vulnerability scanner
      - name: Vulnerability scanner - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/wazuh_modules/vulnerability_scanner

      - name: Vulnerability scanner - Coverage
        uses: ./.github/actions/coverage
        with:
          path: src/wazuh_modules/vulnerability_scanner
          id: vulnerability_scanner

  vulnerability-scanner-modules-asan:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install compatible CMake
        uses: ./.github/actions/reinstall_cmake

      - name: Builder external dependencies
        uses: ./.github/actions/build_external_deps

      - name: Build router
        uses: ./.github/actions/compile
        with:
          path: "src/shared_modules/router"

      - name: Build indexer connector tests
        uses: ./.github/actions/compile
        with:
          path: "src/shared_modules/indexer_connector"

      - name: Build content manager tests
        uses: ./.github/actions/compile
        with:
          path: "src/shared_modules/content_manager"

      # Vulnerability scanner
      - name: Vulnerability scanner - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/wazuh_modules/vulnerability_scanner
          asan: true
