name: 5_testunit_shared_modules_utils

on:
  workflow_dispatch:
  pull_request:
  # Pull request events
    types: [synchronize, opened, reopened, ready_for_review]
  # Path filtering
    paths:
      - ".github/workflows/5_testunit_shared_modules_utils.yml"
      - "src/shared_modules/utils/**"

jobs:
  shared_modules_utils-modules:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel previous runs
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_after_successful_duplicate: 'false'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Project dependencies
        uses: ./.github/actions/build_external_deps

      - name: Shared modules utils - Build tests
        uses: ./.github/actions/build_target_cpp
        with:
          target: "utils_utest"
          test: "true"
          asan: "false"

      - name: Shared modules utils - Run tests
        uses: ./.github/actions/test_cpp
        with:
          valgrind: "true"
          target: "utils_utest"

      - name: Shared modules utils - Coverage
        uses: ./.github/actions/coverage_cpp
        with:
          path: src/shared_modules/utils
          id: utils_utest
          validate_function_coverage: "false"

  shared_modules_utils-asan:
    strategy:
      matrix:
        os: [ ubuntu-24.04, ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Project dependencies
        uses: ./.github/actions/build_external_deps

      - name: Shared modules utils - Build tests
        uses: ./.github/actions/build_target_cpp
        with:
          target: "utils_utest"
          test: "true"
          asan: "true"

      - name: Shared modules utils - Run tests
        uses: ./.github/actions/test_cpp
        with:
          target: "utils_utest"
          valgrind: "false"
