name: Check CHANGELOG

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-changelog:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Check if CHANGELOG.md was modified
        uses: tj-actions/changed-files@v44
        with:
          files: |
            CHANGELOG.md

      - name: Fail if changelog not updated
        if: steps.changed-files.outputs.any_changed != 'true'
        run: |
          echo "‚ùå CHANGELOG not modified. This check can be skipped if the PR changes should not be added to the changelog file."
          exit 1
