name: Engine Integration Test

# Controls when the action will run.
on:
  # Triggers the workflow on pull request but only changes in the src/engine/ directory.
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    paths:
      - 'src/engine/**'
      - '.github/workflows/engine_integration_test.yml'

  workflow_dispatch:
    inputs:
      build_preset:
        type: choice
        description: 'Choose the CMake build preset'
        required: false
        default: 'release'
        options:
          - debug
          - release
          - relwithdebinfo
          - minsize

# Ensures only one instance of this workflow is running per PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  BUILD_PRESET: ${{ github.event.inputs.build_preset || 'release' }}
  ENGINE_DIR: ${{github.workspace}}/src/engine



jobs:
  build:
    name: Engine Integration Test

    # Runs only if the PR status is different to Draft
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:

    - name: Install dependencies lzip
      run: sudo apt-get install lzip

    - name: Check out repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # Disabled due to not being implemented in the current workflow
    # - name: Cache CMake and ccache
    #   uses: hendrikmuhs/ccache-action@v1.2
    #   with:
    #     key: ${{ github.workflow }}-${{ runner.os }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      # Install behave
      run: |
        pip install ${{env.ENGINE_DIR}}/tools/api-communication/
        pip install ${{env.ENGINE_DIR}}/test/engine-test-utils/
        pip install ${{env.ENGINE_DIR}}/test/integration_tests/engine-it

    - name: Setup VCPKG
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: '${{env.ENGINE_DIR}}/vcpkg'
        vcpkgGitCommitId: 'a42af01b72c28a8e1d7b48107b33e4f286a55ef6'
        vcpkgJsonGlob: '${{env.ENGINE_DIR}}/vcpkg.json'

    - name: Configure CMake
      run: cmake --preset=${{env.BUILD_PRESET}} --no-warn-unused-cli -S ${{env.ENGINE_DIR}}

    - name: Create install directory
      run: |
        export WHOAMI=$(whoami)
        sudo install -d -m 0750 -o ${WHOAMI} /var/lib/wazuh-server/
        sudo install -d -m 0750 -o ${WHOAMI} /run/wazuh-server/
        curl -LO http://packages.wazuh.com/deps/vulnerability_model_database/vd_1.0.0_vd_4.10.0.tar.xz
        tar -xvf vd_1.0.0_vd_4.10.0.tar.xz
        mv queue/vd /var/lib/wazuh-server/
        mv queue/vd_updater /var/lib/wazuh-server/
        rm -rf queue vd_1.0.0_vd_4.10.0.tar.xz

    - name: Build
      run: cmake --build ${{env.ENGINE_DIR}}/build --target main -j$(nproc)

    - name: Setup environment
      run: python3 ${{env.ENGINE_DIR}}/test/setupEnvironment.py -e /tmp/actions

    - name: Initial state
      run: engine-it -e /tmp/actions -t ${{env.ENGINE_DIR}}/test/integration_tests/ init --conf ${{env.ENGINE_DIR}}/test/helper_tests/integration_tests/config.env

    - name: Integration Test
      run: engine-it -e /tmp/actions -t ${{env.ENGINE_DIR}}/test/integration_tests/ run
