name: Framework unit tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/framework-unit-tests.yml'
      - 'framework/**'
      - 'src/Makefile'

jobs:
  build: 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
    env:
      PYTHONPATH: /home/runner/work/wazuh/wazuh/apis/server_management:/home/runner/work/wazuh/wazuh/apis/communications:/home/runner/work/wazuh/wazuh/framework
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'framework/requirements-dev.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r framework/requirements-dev.txt --no-build-isolation

      - name: Run Framework tests
        run: python -m pytest framework --cov
