name: Packages - Build WPK packages
on:
  workflow_dispatch:
    inputs:
      docker_image_tag:
        description: |
          Tag name of the Docker image to be downloaded.
          Use 'developer' to set branch name as tag.
          Use 'auto' to set branch version as tag.
          If using a custom tag, use only '-', '_', '.' and alphanumeric characters.
          Default is 'auto'.
        required: false
        default: 'auto'
      linux_reference:
        description: |
          Branch/tag of wazuh/wazuh to build the Linux package
          If empty, it will not be generated.
        required: false
      windows_reference:
        description: |
          Windows WPK name in S3 or URL to download package.
          If empty, it will not be generated.
        required: false
      macos_reference:
        description: |
          MacOS WPK name in S3 or URL to download package.
          If empty, it will not be generated.
        required: false
      revision:
        description: |
          Package revision (name and metadata)
          Default is '0'.
        required: false
        default: '0'
      is_stage:
        description: |
          Should set development/production nomenclature
          True if WPK name should have production format.
          False if WPK name should have developer format.
          Default is 'false'.
        required: false
        type: boolean
        default: false
      checksum:
        description: |
          Generate package checksum
          Default is 'false'.
        required: false
        type: boolean
        default: false

  workflow_call:
    inputs:
      docker_image_tag:
        type: string
        required: false
      linux_reference:
        type: string
        required: false
      windows_reference:
        type: string
        required: false
      macos_reference:
        type: string
        required: false
      revision:
        type: string
        required: false
      is_stage:
        type: boolean
        required: false
      checksum:
        type: boolean
        required: false

jobs:
  WPK-generation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, macos]
        arch: [x86_64]
      fail-fast: false

    steps:
      - name: Cancel previous runs
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_after_successful_duplicate: 'false'

      - uses: actions/checkout@v4

      - name: Set VERSION, CONTAINER_NAME, CHECKSUM_FLAG and UPLOAD_READY
        if: (matrix.os == 'linux' && inputs.linux_reference != '') || (matrix.os == 'windows' && inputs.windows_reference != '') || (matrix.os == 'macos' && inputs.macos_reference != '')
        run: |
          if [ "${{ matrix.os }}" == "linux" ]; then curl -O https://raw.githubusercontent.com/wazuh/wazuh/${{ inputs.linux_reference }}/src/VERSION; echo "VERSION=$(sed 's/.*\([0-9]\.[0-9]*\.[0-9]*\).*/\1/' $GITHUB_WORKSPACE/VERSION)" >> $GITHUB_ENV;
          elif [ "${{ matrix.os }}" == "macos" ]; then echo "VERSION=$(echo "${{ inputs.macos_reference }}" | sed 's/.*\([0-9]\.[0-9]*\.[0-9]*\).*/\1/')" >> $GITHUB_ENV;
          else echo "VERSION=$(echo "${{ inputs.windows_reference }}" | sed 's/.*\([0-9]\.[0-9]*\.[0-9]*\).*/\1/')" >> $GITHUB_ENV; fi
          if [ "${{ matrix.os }}" == "linux" ]; then echo "CONTAINER_NAME=linux_wpk_builder_x86_64" >> $GITHUB_ENV; else echo "CONTAINER_NAME=common_wpk_builder" >> $GITHUB_ENV; fi
          if [ "${{ inputs.checksum }}" == "true" ]; then echo "CHECKSUM_FLAG=-c" >> $GITHUB_ENV; fi
          echo "UPLOAD_READY=no" >> $GITHUB_ENV

      - name: Set TAG
        if: (matrix.os == 'linux' && inputs.linux_reference != '') || (matrix.os == 'windows' && inputs.windows_reference != '') || (matrix.os == 'macos' && inputs.macos_reference != '')
        run: |
          if [ "${{ inputs.docker_image_tag }}" == "auto" ]; then echo "TAG=${{ env.VERSION }}" >> $GITHUB_ENV;
          elif [ "${{ inputs.docker_image_tag }}" == "developer" ]; then echo "TAG=$(sed 's|[/\]|--|g' <<< ${{ github.ref_name }})" >> $GITHUB_ENV;
          else echo "TAG=${{ inputs.docker_image_tag }}" >> $GITHUB_ENV; fi

      - name: Set WPK_NAME
        if: (matrix.os == 'linux' && inputs.linux_reference != '') || (matrix.os == 'windows' && inputs.windows_reference != '') || (matrix.os == 'macos' && inputs.macos_reference != '')
        run: |
          COMMIT_HASH="$(git rev-parse --short HEAD)"
          if [ "${{ matrix.os }}" != "windows" ]; then WPK_ARCH=_${{ matrix.arch }}; fi
          if [ "${{ inputs.is_stage }}" == "true" ]; then echo "WPK_NAME=wazuh_agent_v${{ env.VERSION }}_${{ matrix.os }}${WPK_ARCH}.wpk" >> $GITHUB_ENV;
          else echo "WPK_NAME=wazuh-wpk_${{ env.VERSION }}-${{ inputs.revision }}_${{ matrix.os }}${WPK_ARCH}_${COMMIT_HASH}.wpk" >> $GITHUB_ENV; fi

      - name: Set up AWS CLI
        if: (matrix.os == 'linux' && inputs.linux_reference != '') || (matrix.os == 'windows' && inputs.windows_reference != '') || (matrix.os == 'macos' && inputs.macos_reference != '')
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CI_INTERNAL_DEVELOPMENT_BUCKET_USER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CI_INTERNAL_DEVELOPMENT_BUCKET_USER_SECRET_KEY }}
          aws-region: us-east-1

      - name: Download docker image for WPK building
        if: ((matrix.os == 'linux' && inputs.linux_reference != '') || (matrix.os == 'windows' && inputs.windows_reference != '') || (matrix.os == 'macos' && inputs.macos_reference != ''))
        run: |
          bash $GITHUB_WORKSPACE/.github/actions/ghcr-pull-and-push/pull_image_from_ghcr.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.actor}} ${{ env.CONTAINER_NAME }} ${{ env.TAG }}

      - name: Get secrets by name
        if: ((matrix.os == 'linux' && inputs.linux_reference != '') || (matrix.os == 'windows' && inputs.windows_reference != '') || (matrix.os == 'macos' && inputs.macos_reference != ''))
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |
            WPK_PRIVATE_KEY,${{ secrets.CI_AWS_WPK_PRIVATE_KEY_SECRET_NAME }}
            WPK_CERT,${{ secrets.CI_AWS_WPK_CERT_SECRET_NAME }}

      - name: Build Linux WPK
        if: matrix.os == 'linux' && inputs.linux_reference != ''
        working-directory: packages/wpk
        run: |
          bash generate_wpk_package.sh -t linux --dont-build-docker --tag ${{ env.TAG }} -b ${{ inputs.linux_reference }} -d /tmp --aws-wpk-key WPK_PRIVATE_KEY --aws-wpk-cert WPK_CERT -o ${{ env.WPK_NAME }} -j $(nproc) ${{ env.CHECKSUM_FLAG }}
          echo "UPLOAD_READY=yes" >> $GITHUB_ENV

      - name: Build Windows WPK
        if: matrix.os == 'windows' && inputs.windows_reference != ''
        working-directory: packages/wpk
        run: |
          if [[ "${{ inputs.windows_reference }}" =~ ^http.* ]]; then curl -o wazuh-agent.msi ${{ inputs.windows_reference }}; else aws s3 cp s3://packages-dev.internal.wazuh.com/development/wazuh/4.x/main/packages/${{ inputs.windows_reference }} ./wazuh-agent.msi; fi
          bash generate_wpk_package.sh -t windows --dont-build-docker --tag ${{ env.TAG }} -b ${{ github.ref_name }} -d /tmp --aws-wpk-key WPK_PRIVATE_KEY --aws-wpk-cert WPK_CERT -o ${{ env.WPK_NAME }} -pn ./wazuh-agent.msi -j $(nproc) ${{ env.CHECKSUM_FLAG }}
          echo "UPLOAD_READY=yes" >> $GITHUB_ENV

      - name: Build MacOS WPK
        if: matrix.os == 'macos' && inputs.macos_reference != ''
        working-directory: packages/wpk
        run: |
          if [[ "${{ inputs.macos_reference }}" =~ ^http.* ]]; then curl -o wazuh-agent.pkg ${{ inputs.macos_reference }}; else aws s3 cp s3://packages-dev.internal.wazuh.com/development/wazuh/4.x/main/packages/${{ inputs.macos_reference }} ./wazuh-agent.pkg; fi
          bash generate_wpk_package.sh -t macos --dont-build-docker --tag ${{ env.TAG }} -b ${{ github.ref_name }} -d /tmp --aws-wpk-key WPK_PRIVATE_KEY --aws-wpk-cert WPK_CERT -o ${{ env.WPK_NAME }} -pn ./wazuh-agent.pkg -j $(nproc) ${{ env.CHECKSUM_FLAG }}
          echo "UPLOAD_READY=yes" >> $GITHUB_ENV

      - name: Upload WPK package to S3
        if: env.UPLOAD_READY == 'yes'
        run: |
          aws s3 cp /tmp/${{ env.WPK_NAME }} s3://packages-dev.internal.wazuh.com/development/wazuh/4.x/main/packages/
          if [ "${{ inputs.checksum }}" == "true" ]; then aws s3 cp /tmp/${{ env.WPK_NAME }}.sha512 s3://packages-dev.internal.wazuh.com/development/wazuh/4.x/main/packages/; fi
