name: Packages - Upload WPK images
on:
  workflow_dispatch:
    inputs:
      docker_image_tag:
        description: |
          Tag name of the Docker image to be uploaded.
          Use 'developer' to set branch name as tag.
          Use 'auto' to set branch version as tag.
          If using a custom tag, use only '-', '_', '.' and alphanumeric characters.
          Default is 'auto'.
        required: false
        default: 'auto'

jobs:
  Upload-WPK-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - CONTAINER_NAME: linux_wpk_builder_x86_64
            DOCKERFILE_PATH: packages/wpk/linux/x86_64
          - CONTAINER_NAME: common_wpk_builder
            DOCKERFILE_PATH: packages/wpk/common
      fail-fast: false
    steps:
      - name: Cancel previous runs
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_after_successful_duplicate: 'false'

      - uses: actions/checkout@v4

      - name: Copy scripts to Dockerfile path
        run: |
          cp $GITHUB_WORKSPACE/packages/wpk/run.sh $GITHUB_WORKSPACE/${{ matrix.DOCKERFILE_PATH }}
          cp $GITHUB_WORKSPACE/packages/wpk/wpkpack.py $GITHUB_WORKSPACE/${{ matrix.DOCKERFILE_PATH }}

      - name: Set tag
        run: |
          VERSION=$(sed 's/.*\([0-9]\.[0-9]*\.[0-9]*\).*/\1/' $GITHUB_WORKSPACE/src/VERSION)
          if [ "${{ inputs.docker_image_tag }}" == "auto" ]; then echo "TAG=$VERSION" >> $GITHUB_ENV;
          elif [ "${{ inputs.docker_image_tag }}" == "developer" ]; then echo "TAG=$(sed 's|[/\]|--|g' <<< ${{ github.ref_name }})" >> $GITHUB_ENV;
          else echo "TAG=${{ inputs.docker_image_tag }}" >> $GITHUB_ENV; fi

      - name: Build and push image ${{ matrix.CONTAINER_NAME }} with tag ${{ env.TAG }} to Github Container Registry
        run:
          bash $GITHUB_WORKSPACE/.github/actions/ghcr-pull-and-push/build_and_push_image_to_ghcr.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.actor}} ${{matrix.CONTAINER_NAME}} ${{ matrix.DOCKERFILE_PATH }} ${{ env.TAG }}
