name: Python lint
on: 
  pull_request:
    paths:
      - '.github/workflows/python-lint.yml'
      - 'apis/**/*.py'
      - 'framework/**/*.py'

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/ruff-action@v2
        with:
          # Trick to avoid running the linter and failing in this stage
          args: check --show-settings
      - run: ruff check $(git diff --name-only ${{ github.event.pull_request.base.sha }} -- '*.py')
