name: Syscollector test on Ubuntu

on:
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      # Build wazuh agent for linux.
      - name: Build wazuh agent for linux
        run: |
          rm -rf src/VERSION
          make deps -C src TARGET=agent -j2
          make -C src TARGET=agent -j2
      - name: Install dependencies
        run: |
          pip install -r src/data_provider/requirements.txt
      - name: Run tests
        run: |
          cd src/data_provider
          python -m pytest qa/
