name: Vulnerability Scanner

on:
  pull_request:
    # Pull request events
    types: [synchronize, opened, reopened, ready_for_review]

    # Path filtering
    paths:
      - ".github/workflows/vulnerability-scanner-tests.yml"
      - "src/shared_modules/router/**"
      - "src/shared_modules/content_manager/**"
      - "src/shared_modules/indexer_connector/**"
      - "src/wazuh_modules/vulnerability_scanner/**"
      - "src/wazuh_modules/wazuh-http-request/**"

jobs:
  vulnerability-scanner-modules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Checks which modules have changed
      - name: Check changes
        run: |
          DIFFS=$(git diff --name-only origin/${{ github.head_ref }} origin/${{ github.base_ref }})

          if echo $DIFFS | grep 'src/shared_modules/router/'; then
            echo "ROUTER=true" >> "$GITHUB_ENV"
          else
            echo "ROUTER=false" >> "$GITHUB_ENV"
          fi

          if echo $DIFFS | grep 'src/shared_modules/content_manager/'; then
            echo "CONTENT_MANAGER=true" >> "$GITHUB_ENV"
          else
            echo "CONTENT_MANAGER=false" >> "$GITHUB_ENV"
          fi

          if echo $DIFFS | grep 'src/shared_modules/indexer_connector/'; then
            echo "INDEXER_CONNECTOR=true" >> "$GITHUB_ENV"
          else
            echo "INDEXER_CONNECTOR=false" >> "$GITHUB_ENV"
          fi

          if echo $DIFFS | grep 'src/wazuh_modules/vulnerability_scanner/'; then
            echo "VULNERABILITY_SCANNER=true" >> "$GITHUB_ENV"
          else
            echo "VULNERABILITY_SCANNER=false" >> "$GITHUB_ENV"
          fi

      - name: Prepare dependencies
        run: |
          cd src
          make deps TARGET=server -j2
          make build_gtest TARGET=server -j2
          make libwazuhext.so TARGET=server -j2

          cd shared_modules/http-request
          mkdir -p build && cd build && cmake .. && make

      ########################
      # Compilation and test #
      ########################

      # Router
      - name: Router
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/router

      # indexer connector
      - name: Indexer connector
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/content_manager

      # content manager
      - name: Content manager
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/indexer_connector

      # Vulnerability scanner
      - name: Vulnerability scanner
        uses: ./.github/actions/compile_and_test
        with:
          path: src/wazuh_modules/vulnerability_scanner
