name: Vulnerability Scanner

on:
  pull_request:
  # Pull request events
    types: [synchronize, opened, reopened, ready_for_review]
  # Path filtering
    paths:
      - ".github/workflows/vulnerability-scanner-tests.yml"
      - "src/shared_modules/router/**"
      - "src/shared_modules/content_manager/**"
      - "src/shared_modules/indexer_connector/**"
      - "src/wazuh_modules/vulnerability_scanner/**"
      - "src/wazuh_modules/http-request/**"

jobs:
  style-and-documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0 # We need to fetch all the history to calculate the deltas.

      # Check which modules have been modified.
      # Could be used to avoid some steps if possible (Doxygen, Style, etc.)
      - name: Calculate deltas
        run: |

          DIFFS=""
          
          # Get the list of modified files
          if [ -z ${{ env.ACT }} ]; then
            # CI execution
            DIFFS=$(git diff --name-only HEAD origin/${{ github.base_ref }})
            # Local execution
          else
            if [ -n "${{ env.REF_BRANCH }}" ]; then
              # If REF_BRANCH is set, use it to calculate the diff
              DIFFS=$(git diff --name-only HEAD origin/${{ env.REF_BRANCH }})  
            else
              # If REF_BRANCH is not set, use main as base 
              DIFFS=$(git diff --name-only HEAD origin/main)  
            fi
          fi

          if echo $DIFFS | grep 'src/shared_modules/router/'; then
            echo "ROUTER=true" >> "$GITHUB_ENV"
          fi

          if echo $DIFFS | grep 'src/shared_modules/content_manager/'; then
            echo "CONTENT_MANAGER=true" >> "$GITHUB_ENV"
          fi

          if echo $DIFFS | grep 'src/shared_modules/indexer_connector/'; then
            echo "INDEXER_CONNECTOR=true" >> "$GITHUB_ENV"
          fi

          if echo $DIFFS | grep 'src/wazuh_modules/vulnerability_scanner/'; then
            echo "VULNERABILITY_SCANNER=true" >> "$GITHUB_ENV"
          fi

      # Router
      - name: Router - Coding style
        if: env.ROUTER
        uses: ./.github/actions/clang_format
        with:
          path: src/shared_modules/router
          id: router

      - name: Router - Doxygen
        if: env.ROUTER
        uses: ./.github/actions/doxygen
        with:
          path: src/shared_modules/router
          id: router

      # Indexer connector
      - name: Indexer connector - Coding style
        if: env.INDEXER_CONNECTOR
        uses: ./.github/actions/clang_format
        with:
          path: src/shared_modules/indexer_connector
          id: indexer_connector

      - name: Indexer connector - Doxygen
        if: env.INDEXER_CONNECTOR
        uses: ./.github/actions/doxygen
        with:
          path: src/shared_modules/indexer_connector
          id: indexer_connector

      # Content manager
      - name: Content manager - Coding style
        if: env.CONTENT_MANAGER
        uses: ./.github/actions/clang_format
        with:
          path: src/shared_modules/content_manager
          id: content_manager

      - name: Content manager - Doxygen
        if: env.CONTENT_MANAGER
        uses: ./.github/actions/doxygen
        with:
          path: src/shared_modules/content_manager
          id: content_manager

      # Vulnerability scanner
      - name: Vulnerability scanner - Coding style
        if: env.VULNERABILITY_SCANNER
        uses: ./.github/actions/clang_format
        with:
          path: src/wazuh_modules/vulnerability_scanner
          id: vulnerability_scanner

      - name: Vulnerability scanner - Doxygen
        if: env.VULNERABILITY_SCANNER
        uses: ./.github/actions/doxygen
        with:
          path: src/wazuh_modules/vulnerability_scanner
          id: vulnerability_scanner

  vulnerability-scanner-modules:
    needs: style-and-documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Project dependencies
        uses: ./.github/actions/vulnerability_scanner_deps

      ########################
      # Compilation and test #
      ########################

      # Router
      - name: Router - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/router

      - name: Router - Coverage
        uses: ./.github/actions/coverage
        with:
          path: src/shared_modules/router
          id: router

      # Indexer connector
      - name: Indexer connector - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/indexer_connector

      - name: Indexer connector - Coverage
        uses: ./.github/actions/coverage
        with:
          path: src/shared_modules/indexer_connector
          id: indexer_connector

      # Content manager
      - name: Content manager - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/content_manager

      - name: Content manager - Coverage
        uses: ./.github/actions/coverage
        with:
          path: src/shared_modules/content_manager
          id: content_manager

      # Vulnerability scanner
      - name: Vulnerability scanner - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/wazuh_modules/vulnerability_scanner

      - name: Vulnerability scanner - Coverage
        uses: ./.github/actions/coverage
        with:
          path: src/wazuh_modules/vulnerability_scanner
          id: vulnerability_scanner

  vulnerability-scanner-modules-asan:
    needs: style-and-documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Project dependencies
        uses: ./.github/actions/vulnerability_scanner_deps         

      ########################
      # Compilation and test #
      ########################

      # Router
      - name: Router
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/router
          asan: "true"

      # indexer connector
      - name: Indexer connector
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/content_manager
          asan: "true"

      # content manager
      - name: Content manager
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/indexer_connector
          asan: "true"

      # Vulnerability scanner
      - name: Vulnerability scanner
        uses: ./.github/actions/compile_and_test
        with:
          path: src/wazuh_modules/vulnerability_scanner
          asan: "true"
